FOOD_DESCRIPTION_FILE_PATH = 'sr28asc/FOOD_DES.txt'
GROUP_DESCRIPTION_FILE_PATH = 'sr28asc/FD_GROUP.txt'
NUTRIENT_DEFINITION_FILE_PATH = 'sr28asc/NUTR_DEF.txt'
NUTRIENT_DATA_FILE_PATH = 'sr28asc/NUT_DATA.txt'

TRANSLATION_LANGUAGES = ['ru']

FOOD_FILE = 'food.json'
FOOD_I18N_FILE = 'food_i18n.json'
CATEGORIES_FILE = 'categories.json'
CATEGORIES_I18N_FILE = 'categories_i18n.json'

DB_NAME = 'easy_diet'
DB_USERNAME = 'postgres'
DB_PASSWORD = 'postgres'
DB_HOST = 'localhost'
DB_PORT = '5432'